config/routes.rb
Rails.application.routes.draw do
  get 'good_things/index'
  devise_for :users
  root to: 'life_charts#index'
  post '/life_charts/guest_sign_in', to: 'life_charts#new_guest'
  resources :good_things, only: [:index,:create,:update,:show,:new,:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/good_thing.rb
class GoodThing < ApplicationRecord
  belongs_to :user
  with_options presence: true do
    validates :start_date, uniqueness: true
    validates :good_1
    validates :good_2
    validates :good_3
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :good_thing

  with_options presence: true do
    validates :nickname, :password_confirmation
    validates :email, uniqueness: true
    validates :email, exclusion: { in: ['@'] }
    validates :password, length: { minimum: 6 }
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/good_things_controller.rb
class GoodThingsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :create, :show]

  def index
    @good_things = GoodThing.where(user: current_user.id)
    @good_thing = GoodThing.new
  end

  def new
  end

  def create
    @good_thing = GoodThing.new(good_thing_params)

    if @good_thing.save
      redirect_to good_things_index_path
    else
      render :index
    end
  end

  def show
    @good_thing = GoodThing.find(params[:id])
  end

  def destroy
    @good_thing = GoodThing.find(params[:id])
    if @good_thing.destroy
      redirect_to good_things_index_path
    else
      render :show
    end
  end

  private

  def good_thing_params
    params.require(:good_thing).permit(:good_1, :good_2, :good_3, :start_date).merge(user_id: current_user.id)
  end
end

app/controllers/life_charts_controller.rb
class LifeChartsController < ApplicationController
  def index
  end

  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.nickname = 'Guest'
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
    end
    sign_in user
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/good_things_helper.rb
module GoodThingsHelper
end

app/helpers/life_charts_helper.rb
module LifeChartsHelper
end

app/views/good_things/_form_new.html.erb
<div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">今日よかったことを投稿しましょう！</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
</div>

<%= form_with(model: @good_thing,url:good_things_path, local: true) do |form| %>
  <div class="field">
    <%= form.label :good_1 %>
    <%= form.text_field :good_1 %>
  </div>

  <div class="field">
    <%= form.label :good_2 %>
    <%= form.text_field :good_2 %>
  </div>

  <div class="field">
    <%= form.label :good_3 %>
    <%= form.text_field :good_3 %>
  </div>

  <div id="start-date">
    <%#= form.label :start_date %>
    <%#= form.datetime_select :start_date %>
  </div>

  <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= form.submit "登録する",class:"btn btn-primary"%>
  </div>

      <% end %>

app/views/good_things/index.html.erb
<div class="body">
  <%= link_to "トップページへ戻る",root_path,class:"text-white"%>
  <div class="d-flex justify-content-center">
    <div class="w-75 h-75 ">
      <div id='calendar'></div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="good_thing_Modal" tabindex="-1" role="dialog" aria-labelledby="good_thing_ModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="good_thing_ModalLabel">今日よかったことを投稿しましょう！</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= form_with(model: @good_thing,url:good_things_path, local: true) do |form| %>
        <%= render 'shared/error_messages', model: form.object %>
          <div class="field">
            <%= form.label :good_1 %>
            <%= form.text_field :good_1 %>
          </div>

          <div class="field">
            <%= form.label :good_2 %>
            <%= form.text_field :good_2 %>
          </div>

          <div class="field">
            <%= form.label :good_3 %>
            <%= form.text_field :good_3 %>
          </div>

          <div id="start-date">
            <%#= form.label :start_date %>
            <%#= form.datetime_select :start_date %>
          </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
        <%= form.submit "投稿する",class:"btn btn-primary"%>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/good_things/show.html.erb
<div class="body">
  <div class ="container d-flex flex-column align-items-center">


    <h2 class="text-white justify-content-center">今日の良かったこと</h2>
    <div class="text-white">
      <%= @good_thing.good_1 %>
    </div>
    <div class="text-white">
      <%= @good_thing.good_2 %>
    </div>
    <div class="text-white">
      <%= @good_thing.good_3 %>
    </div>
    <%= link_to '削除', good_thing_path, method: :delete%>
    <%= link_to '戻る', good_things_path%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SelfEsteem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/life_chart/index.html.erb
<header class="header bg-info">
  <div class ="container">
    <div class="row">
        <div class = "header-left col-4">
          <h1 class= "mt-1 text-white">Self-esteem</h1>
        </div>
        <div class = "col-8 ">
          <ul class = "list-group list-group-horizontal float-right pt-1">
            <% if user_signed_in? %>
              <li class="list-group-item bg-info"><%= link_to current_user.nickname, "#", class: "user-nickname text-white-50" %></li> 
              <li class="list-group-item bg-info"><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "logout text-white-50" %></li> 
            <% else %>
              <li class="list-group-item bg-info"><%= link_to 'Log in', new_user_session_path, class: "login text-white-50" %></li>
              <li class="list-group-item bg-info"><%= link_to 'Sign up', new_user_registration_path, class: "sign-up text-white-50" %></li>
            <% end %>
          </ul>
        </div>
    </div>
 </div>
</header>

app/views/life_charts/index.html.erb
<div class ="body">
  <div class="header">
      <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-info  shadow-sm">
      <h2 class="my-0 mr-md-auto font-weight-normal text-white">Self-esteem</h1>
      <nav class="my-2 my-md-0 mr-md-3">
        <% if user_signed_in? %>
          <%= link_to current_user.nickname, "#", class: "user-nickname text-white p-2" %>  
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "logout text-white p-2" %>
        <% else %>
          <%= link_to 'Log in', new_user_session_path, class: "login text-white p-2" %>
          <%= link_to 'Sign up', new_user_registration_path, class: "sign-up text-white p-2" %>
          <%= link_to 'Guest Log in', life_charts_guest_sign_in_path, class: "login text-white p-2", method: :post %>
        <% end %>
      </nav>
    </div>
  </div>

  <div class="container">
    <div class="left">
      <h3 class="text-white p-5">自分のことを<br>もっと褒めてあげませんか？<h3>
      <div class="pl-5">
        <p class="text-white h6">
          どんな小さいことでも構いません。
          <br>毎日書くことで、自分に自信が持てるようになってきます。
        </p>
      </div>
    </div>

    <div class="mt-5">
      <button type="button" class="text-white ml-5 btn border-light btn-outline-primary" data-toggle="modal" data-target="#usageModal">
         使い方
      </button>
    </div>
    <div class="left p-5">
       <%=link_to "今日良かったことを投稿する",good_things_index_path, class:"btn text-white border-light btn-outline-primary",type:"button"%>
    </div>
</div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top border-white fixed-bottom container">
      <div class="row">
        <div class="col-6 col-md text-white">
          <h5>このサービスについて</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-white" href="#">プライバシー</a></li>
            <li><a class="text-white" href="#">利用規約</a></li>
          </ul>
        </div>
      </div>
    </footer>
  </div>

</div>

<div class="modal fade" id="usageModal" tabindex="-1" role="dialog" aria-labelledby="usageModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="usageModalLabel">使い方</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>①Sign upをクリックしていただき、新規登録をお願いいたします。<br>※お試しの場合は、Guest Log inを押下してください。</p>
        
        <p>②カレンダー内の日付をクリックすると、投稿画面が表示されます。</p>
        <p>③投稿すると、カレンダー内に投稿詳細画面が表示されます。</p><br>
        ※全ての機能を使うためにはログインが必須となります
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>